#!/bin/bash
javac -classpath ".:common-1.8.3.jar:junit-4.10.jar:model-1.8.3.jar:swingui-1.8.3.jar:hsqldb-1.8.0.10.jar" eecs4313a2b/*.java &&
java -cp ".:common-1.8.3.jar:junit-4.10.jar:model-1.8.3.jar:swingui-1.8.3.jar:hsqldb-1.8.0.10.jar:." org.junit.runner.JUnitCore eecs4313a2b.EECS4313A2AllBlackBoxTests
